version: 1.0.{build}
build_script:
- ps: >-
    dotnet build Anetta/Anetta.csproj
after_test:
- ps: >-
    dotnet pack Anetta/Anetta.csproj -c Release --include-symbols
artifacts:
- path: Anetta/bin/Release/*.nupkg
  name: Anetta
deploy:
- provider: NuGet
  api_key:
    secure: HatA8lH7GwAGuVEwLUL8mYA29zB8SD+GfYZv2sowexXoJ9fezoT9F7xlZ7YeT7Eg
  skip_symbols: true